### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by filipiz** [romainberger/yeoman-wordpress#1]
Guys.
I just need a help to install this generator..

Can you add instructions on the README.md?

I tried to install via NPM. 
It found and installed the package, but when I run 

```
$ yeoman init yeoman-wordpress
```

I get..

```
Could not find generator yeoman-wordpress
Tried in: ...
```

**Comment by romainberger** [comment]
Hi,

The npm version is not up to date, you should clone it from the repo directly.

Try this:

```
$ cd /usr/local/lib/node_modules/yeoman/lib
```

Check if there is a directory named `generators`. If not, create it.
Then cd into the generators directory and run

```
$ sudo git clone git://github.com/romainberger/yeoman-wordpress.git
```

It should work. Yeoman look for in several places for the generators (https://github.com/yeoman/generators/issues/1#issuecomment-8194660) but cloning it here will allow you to use it globally, so you don't have to download it every time you want to use it.

I didn't write it in the readme because I think it's a bit dirty to do it this way, but I probably should.

**Comment by filipiz** [comment]
Thankyou Romain!
Great.

I'll probably contribute to the project. By now, just getting in touch and making it work.

Cheers!
