### ISSUE TITLE
Question about build process

### ISSUE THREAD

**Issue by jahvi** [romainberger/yeoman-wordpress#6]
For what I can tell the build process only minifies images for now is this correct? I'm new with yeoman/grunt so I really can't tell from the gruntfile

**Comment by romainberger** [comment]
For now it minifies images and the css files. The build task is not completely working and still needs some work.

**Comment by jahvi** [comment]
Thanks, that's what I thought, I image the js part would be a challenge at least it'd require to include the `<script>` tags directly instead of using `wp_enqueue_scripts()`

**Comment by pgom** [comment]
You can create a task to parse the file where the css/js files are enqueued and replace it with the minified files.

**Comment by romainberger** [comment]
> You can create a task to parse the file where the css/js files are enqueued and replace it with the minified files.

Yes I think it's the easiest way to do it.
I will try to override the Yeoman build task to perform this, and I will certainly use the build task from the project you showed me ( https://github.com/retlehs/roots/tree/grunt ) as a base.
If I can find some time to do it I will start working on that this week end.

**Comment by pgom** [comment]
Yeps...and (as mentioned earlier) the only way i could find to make it work is to create a new build task where the yeoman ones are defined. It would be great if you can register a custom task on your Gruntfile but from what I could understand it's not possible...right now, at least.

**Comment by romainberger** [comment]
Apparently it is. I did'nt take a look at how it is done yet, but mklabs overrides the server task in his Jekyll generator.
https://github.com/mklabs/yeoman-jekyll

**Comment by pgom** [comment]
Oh great...I'll take a look as soon as i can!

**Comment by romainberger** [comment]
Overriding a task is actually really easy. I created a branch to work later on the build task. For now it was to test how this works.
https://github.com/romainberger/yeoman-wordpress/tree/build_script

**Comment by pgom** [comment]
I've managed to a similar approach by registering a task 'build' and defining the tasks wanted which overrides the yeoman default build. It's better than my first approach but for me it's not ideal because it messes with the yeoman defaults.

**Comment by romainberger** [comment]
> It's better than my first approach but for me it's not ideal because it messes with the yeoman defaults.

Do you mean your approach is better or the way I did?
I just did the exact same way mklabs did in his generator. And does not seems to create any conflict with yeoman's defaults tasks, although I had to add a `process.exit()` at the end because if you don't the yeoman tasks is still performed after.

**Comment by pgom** [comment]
I was talking about my first approach...not yours. Sorry for the misunderstanding. I guess your way is the ideal way of doing it...

**Comment by jahvi** [comment]
Great, let us know when we can test it, if I can't help with the coding that's the least I can do :+1:

**Comment by romainberger** [comment]
Well, I experimented a little, and it seems to be harder than I thought.
The build task parse the file where the css and js files are enqueued but this file can be named differently for every theme. I guess it has to be defined in a config var in the gruntfile.
Then for each css / js file, the task hashes the file and update the filename. Once again the number of file and there name can be anything so it would require to parse the directories to get all the css and js files, then run the process for each one.
So that's the first thing.
Then apparently I was wrong, the yeoman build task is not performed after the build task we add, but at the same time.
It means we won't have to care of the css minification, image optimisation and such, but we have to be sure not to create conflicts between the two.

**Comment by romainberger** [comment]
I am closing these issues as I haven't made any progress on the build task and don't plan to make any.
I personnaly avoid as much as possible working with Wordpress right now and don't use this generator very often,
so I don't have a need for this.

I still keep the `build` branch if anyone is interested and I will continue to update and fix the issues in the generator if there are some.
